name: Build Release Image

on: push

jobs:
  build_release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - run: go build
      - uses: actions/upload-artifact@v2
        with:
          name: build_release
          path: fakemoderun.exe

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ build_release ]
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: build_release
          path: .
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: fakemoderun.exe
